const { PubSub } = require('graphql-subscriptions');

const DEVICE_TYPES_UPDATED = 'DEVICE_TYPES_UPDATED';
const DEVICES_UPDATED = 'DEVICES_UPDATED';
const TRIALS_UPDATED = 'TRIALS_UPDATED';
const ASSETS_UPDATED = 'ASSETS_UPDATED';
const TRIALSETS_UPDATED = 'TRIALSETS_UPDATED';
const EXPERIMENTS_UPDATED = 'EXPERIMENTS_UPDATED';
const DATAS_UPDATED = 'DATAS_UPDATED';

module.exports = {
  pubsub: new PubSub(),
  DEVICE_TYPES_UPDATED,
  TRIALS_UPDATED,
  DEVICES_UPDATED,
  ASSETS_UPDATED,
  TRIALSETS_UPDATED,
  EXPERIMENTS_UPDATED,
  DATAS_UPDATED,
};
