const { PubSub } = require('graphql-subscriptions');

const ENTITIES_TYPES_UPDATED = 'ENTITIES_TYPES_UPDATED';
const ENTITIES_UPDATED = 'ENTITIES_UPDATED';
const TRIALS_UPDATED = 'TRIALS_UPDATED';
const ASSETS_UPDATED = 'ASSETS_UPDATED';
const TRIALSETS_UPDATED = 'TRIALSETS_UPDATED';
const EXPERIMENTS_UPDATED = 'EXPERIMENTS_UPDATED';
const DATAS_UPDATED = 'DATAS_UPDATED';

module.exports = {
  pubsub: new PubSub(),
  ENTITIES_TYPES_UPDATED,
  TRIALS_UPDATED,
  ENTITIES_UPDATED,
  ASSETS_UPDATED,
  TRIALSETS_UPDATED,
  EXPERIMENTS_UPDATED,
  DATAS_UPDATED,
};
